# 11 June 2026 CW

In [22]:
import numpy as np

In [23]:
a = np.array([1, 2, 3], dtype=np.int32)
print(a)

[1 2 3]


In [24]:
b= np.array([[9.0,8.0,7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [25]:
a.ndim

1

In [26]:
b.shape

(2, 3)

In [27]:
a.dtype

dtype('int32')

In [28]:
a= np.array([1,2,3])
a.size

3

In [29]:
a.itemsize

8

In [30]:
a.nbytes

24

In [31]:
a.size

3

In [32]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [33]:
a[1, 5]

np.int64(13)

In [34]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
a[:, 2]

array([ 3, 10])

In [36]:
a[0, 1:6:2]

array([2, 4, 6])

In [37]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [38]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [39]:
name = ['Alice', 'Bob', 'Cathy', 'John']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

# Use a compound data type for structured arrays

data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
'formats':('U10', 'i4', 'f8')})
print(data.dtype)

data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('John', 19, 61.5)]


In [40]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
b[0,1,1]

np.int64(4)

In [43]:
b[0,1]=[3,9]
b[0,0]=[1,1]
b[0, :, 1]=[9]
b[0,:, 0]=[9,9]
b

array([[[9, 9],
        [9, 9]],

       [[5, 6],
        [7, 8]]])

In [44]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [47]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [49]:
np.random.rand(4,2)

array([[0.49642292, 0.82039578],
       [0.44397951, 0.27987673],
       [0.10541705, 0.85630458],
       [0.91476517, 0.91198644]])

In [51]:
np.random.randint(-4,8, size=(3,3))

array([[ 1, -2,  5],
       [-3, -1, -3],
       [ 1,  2, -1]], dtype=int32)

In [53]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [55]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [60]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


In [61]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [62]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [63]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.min(stats)


np.int64(1)

In [65]:
np.max(stats, axis=1)


array([3, 6])

In [66]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [67]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [68]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])